(ns api-modeling-framework.generators.domain.openapi-test
  #?(:cljs (:require-macros [cljs.test :refer [deftest is async]]))
  (:require #?(:clj [clojure.test :refer :all])
            [api-modeling-framework.model.vocabulary :as v]
            [api-modeling-framework.model.document :as document]
            [api-modeling-framework.model.domain :as domain]
            [api-modeling-framework.generators.domain.openapi :as generator]
            [api-modeling-framework.generators.document.openapi :as document-generator]
            [api-modeling-framework.parser.document.openapi :as openapi-document-parser]
            [api-modeling-framework.parser.domain.openapi :as openapi-parser]
            [api-modeling-framework.generators.domain.common :as common]
            [api-modeling-framework.parser.domain.raml :as raml-parser]))

(deftest clean-autogenerated-gets
  (is (= nil (generator/clean-auto-generated nil)))
  (is (= nil (generator/clean-auto-generated {})))
  (is (= nil (generator/clean-auto-generated [])))
  (is (= :test (generator/clean-auto-generated :test)))
  (is (= nil (generator/clean-auto-generated {:x-generated true})))
  (is (= nil (generator/clean-auto-generated {:x-generated true
                                              :test true})))
  (is (= {:test 1} (generator/clean-auto-generated {:test 1
                                                    :other {:x-generated true
                                                            :test true}})))
  (is (= nil (generator/clean-auto-generated {:other {:multiple {:x-generated true
                                                                 :test true}}}))))

(deftest to-openapi-APIDocumentation
  (let [api-documentation (domain/map->ParsedAPIDocumentation {:host "test.com"
                                                               :scheme ["http" "https"]
                                                               :base-path "/path"
                                                               :accepts ["application/json"]
                                                               :content-type ["appliaton/json"]
                                                               :version "1.0"
                                                               :terms-of-service "terms"
                                                               :id "id"
                                                               :name "name"
                                                               :description "description"})]
    (is (= {:swagger "2.0"
            :host "test.com"
            :schemes ["http" "https"]
            :basePath "/path"
            :produces "appliaton/json"
            :info
            {:title "name"
             :description "description"
             :version "1.0"
             :termsOfService "terms"}
            :paths {}
            :consumes "application/json"}
           (generator/to-openapi api-documentation {})))))

(deftest to-openapi-APIDocumentation-with-amf
  (let [api-documentation (domain/map->ParsedAPIDocumentation {:host "test.com"
                                                               :scheme ["http" "https"]
                                                               :base-path "/path"
                                                               :accepts ["application/json"]
                                                               :content-type ["appliaton/json"]
                                                               :version "1.0"
                                                               :terms-of-service "terms"
                                                               :id "model-id"
                                                               :name "name"
                                                               :description "description"})
        generated (generator/to-openapi api-documentation {:syntax :openapi :generate-amf-info true})]
    (is (= "model-id" (:x-amf-id generated)))
    (is (= "http://raml.org/vocabularies/http#APIDocumentation" (:x-amf-class generated)))))

(deftest to-openapi-EndPoint
  (let [node {:swagger "2.0"
              :info {:title "title"
                     :description "description"
                     :termsOfService "terms-of-service"
                     :version "2.0"}
              :host "api.test.com"
              :basePath "/test/endpoint"
              :x-baseUriParameters [{:name "bucket"
                                     :in "domain"
                                     :type "string"}]
              :schemes ["http" "https"]
              :consumes ["application/json" "application/xml"]
              :produces ["application/ld+json"]
              :paths {(keyword "/users") {:get {}}
                      (keyword "/users/items") {:get {}}}}
        parsed (openapi-parser/parse-ast node {:location "file://path/to/resource.raml#"
                                               :parsed-location "file://path/to/resource.raml#"
                                               :is-fragment false})
        generated (generator/to-openapi parsed {})]
    (is (= (->> node :paths keys)
           (->> generated :paths keys)))))

(deftest to-openapi-operations
  (let [node {:get {:operationId "get"
                    :description "get description"
                    :schemes ["https"]
                    :tags ["experimantl" "foo" "bar"]
                    :produces ["application/ld+json"]
                    :consumes ["application/json"]
                    :responses {"default" {:description ""}}}
              :post {:operationId "post"
                     :description "post description"
                     :schemes ["https"]
                     :tags ["experimantl" "foo" "bar"]
                     :produces ["application/ld+json"]
                     :consumes ["application/json"]
                     :responses {"default" {:description ""}}}}
        parsed (openapi-parser/parse-ast node {:location "file://path/to/resource.raml#/users"
                                               :parsed-location "file://path/to/resource.raml#/users"
                                               :is-fragment false
                                               :path "/Users"})
        generated (generator/to-openapi parsed {})]
    (is (= node generated))))

(deftest to-openapi-response
  (let [node {:operationId "get method"
              :description "get description"
              :schemes ["http"]
              :responses {"200" {:description "200 response"}
                          "400" {:description "400 response"}}}
        parsed (openapi-parser/parse-ast node {:location "file://path/to/resource.raml#/users"
                                               :parsed-location "file://path/to/resource.raml#/users"
                                               :is-fragment false
                                               :path "/Users"})
        generated (generator/to-openapi parsed {})]
    (is (= node generated)))
  (let [parsing-context {:parsed-location "file://path/to/resource.raml#/api-documentation/resources/0"
                         :location "file://path/to/resource.raml#/users"
                         :path "/users"
                         :is-fragment false}
        node {:displayName "get method"
              :description "get description"
              :protocols ["http"]
              :responses {200 {:description "200 response"
                               :body {"application/json" {:type "string"}
                                      "text/plain"       {:type "string"}}}
                          400 {:description "400 response"
                               :body {:type "string"}}}}
        expected {:operationId "get method"
                  :description "get description"
                  :schemes ["http"]
                  :responses
                  {"200"
                   {:description "200 response"
                    :schema {:type "string"}
                    :x-media-type "application/json"
                    :x-response-payloads
                    [{:x-media-type "text/plain",
                      :schema {:type "string"}}]}
                   "400" {:description "400 response"
                          :schema {:type "string"}}}}
        parsed (raml-parser/parse-ast node parsing-context)
        generated (generator/to-openapi parsed {})]

    (is (= expected
           generated))))

(deftest top-openapi-method-with-params
  (let [node {:get {:operationId "get"
                    :description "get description"
                    :schemes ["https"]
                    :tags ["experimantl" "foo" "bar"]
                    :produces ["application/ld+json"]
                    :consumes ["application/json"]
                    :responses {"default" {:description ""}}
                    :parameters [{:name "api-key"
                                  :in "header"
                                  :type "string"}
                                 {:name "petId"
                                  :in "path"
                                  :required true
                                  :type "string"}
                                 {:name "race"
                                  :in "query"
                                  :type "string"}
                                 {:name "the-body"
                                  :in "body"
                                  :schema {:type "string"}}]}
              :post {:operationId "post"
                     :description "post description"
                     :schemes ["https"]
                     :tags ["experimantl" "foo" "bar"]
                     :produces ["application/ld+json"]
                     :consumes ["application/json"]
                     :responses {"default" {:description ""}}}}
        parsed (openapi-parser/parse-ast node {:location "file://path/to/resource.raml#/users"
                                               :parsed-location "file://path/to/resource.raml#/users"
                                               :is-fragment false
                                               :path "/Users"})
        generated (generator/to-openapi parsed {})]
    (is (= generated node))))

(deftest from-traits-test
  (let [input {:swagger "2.0",
               :host "test.com"
               :schemes ["http" "https"]
               :info
               {:title "name"
                :description "description"
                :version "1.0"
                :termsOfService "terms"}
               :x-traits {:secure {:parameters [{:name "access_token"
                                                 :in "header"
                                                 :required true
                                                 :type "string"}]
                                   :x-abstract-node true}}
               :paths {(keyword "/users/items") {:x-is [{:$ref "#/x-traits/secure"}]
                                                 :get {:operationId "get"
                                                       :description "get description"
                                                       :schemes ["https"]
                                                       :tags ["experimantl" "foo" "bar"]
                                                       :produces ["application/ld+json"]
                                                       :consumes ["application/json"]
                                                       :responses {"default" {:description ""}}
                                                       :parameters [{:name "petId"
                                                                     :in "path"
                                                                     :required true
                                                                     :type "string"}
                                                                    {:name "race"
                                                                     :in "query"
                                                                     :type "string"}
                                                                    {:name "the-body"
                                                                     :in "body"
                                                                     :schema {:type "string"}}]}}}}
        traits (openapi-parser/process-traits input {:location "file://location/#"
                                                     :fragments []
                                                     :document-parser openapi-document-parser/parse-ast
                                                     :parsed-location "file://location#"})
        api-documentation (openapi-parser/parse-ast input
                                                    {:location "file://location#"
                                                     :parsed-location "file://location#"
                                                     :base-uri "file://location"
                                                     :references traits
                                                     :is-fragment false})
        output (generator/to-openapi api-documentation {:references (vals traits)
                                                        :fragments {}
                                                        :document-generator document-generator/to-openapi})]
    (is (= input output))))

(deftest annotation?-test
  (is (openapi-parser/annotation? :x-annotation))
  (is (not (openapi-parser/annotation? :not-annotation))))

(deftest with-annotations-test
  (let [node {:title "Users"
              :x-testHarness "usersTest"
              :get {:title "get method"
                    :description "get description"}}
        model (domain/map->ParsedEndPoint {})
        annotations (atom {})
        context {:base-uri "http://base-uri"
                 :annotations annotations
                 :parsed-location "http://base-uri#/somewhere"}
        parsed (openapi-parser/with-annotations node context model)]
    (is (= "testHarness" (-> @annotations (get "testHarness") :name)))
    (is (= {"@value" "usersTest"} (-> parsed document/additional-properties first domain/object)))
    (is (= "http://base-uri#/x-annotationTypes/testHarness" (-> parsed document/additional-properties first domain/predicate)))))

(deftest to-openapi-Annotations
  (let [base-uri "file://path/to/resource.openapi"
        location "file://path/to/resource.openapi#"
        annotations (atom {})
        input {:paths {(keyword "/users") {:get {:x-testHarness "usersTest"
                                                 :description "get description"
                                                 :responses {:default {:x-generated true, :description ""}}}}}
               :info {:version ""},
               :swagger "2.0"}
        parsed (openapi-parser/parse-ast input
                                      {:location location
                                       :parsed-location "file://path/to/resource.openapi#"
                                       :is-fragment false
                                       :annotations annotations
                                       ;:annotations annotations
                                       :path "/test"})
        parsed-operation (-> parsed domain/endpoints first :supported-operations first)
        generated-annotations (common/model->annotationTypes (vals @annotations) {} generator/to-openapi!)
        generated (assoc (generator/to-openapi parsed {})
                         :x-annotationTypes generated-annotations)]

    (is (= "testHarness" (-> @annotations (get "testHarness") :name)))

    (is (= {"@value" "usersTest"} (-> parsed-operation
                                      document/additional-properties
                                      first domain/object)))

    (is (= "#/x-annotationTypes/testHarness" (-> parsed-operation
                                                 document/additional-properties
                                                 first domain/predicate)))
    (is (= ["http://www.w3.org/ns/hydra/core#Operation"]
           (-> @annotations (get "testHarness") domain/domain)))

    (is (= "usersTest" (-> generated :paths (get (keyword "/users")) :get :x-testHarness)))))
